# typed: false
# frozen_string_literal: true

# This file is auto-generated by the ivygrep release workflow. DO NOT EDIT.
class IvygrepStatic < Formula
  desc "Semantic grep for codebases — statically linked (musl) variant"
  homepage "https://github.com/bvolpato/ivygrep"
  version "0.5.32"
  license "MIT"

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bvolpato/ivygrep/releases/download/v0.5.32/ivygrep-v0.5.32-linux-x86_64-musl.tar.gz"
      sha256 "ef78161f4acb41daf92a6ae196574a1b270bcf777369412e4be484a664d41133"
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvolpato/ivygrep/releases/download/v0.5.32/ivygrep-v0.5.32-linux-aarch64-musl.tar.gz"
      sha256 "5dc59dbc3e7101a3b962fb39572a3202cbd8ecf54e6c5c01892aae621bb82d5f"
    end
  end

  def install
    bin.install "ig"
  end

  test do
    (testpath/"hello.rs").write('fn hello() -> &str { "world" }')
    system "#{bin}/ig", "--help"
  end
end
