# typed: false
# frozen_string_literal: true

# This file is auto-generated by the ivygrep release workflow. DO NOT EDIT.
class Ivygrep < Formula
  desc "Semantic grep for codebases — hybrid lexical + vector search, local-only"
  homepage "https://github.com/bvolpato/ivygrep"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bvolpato/ivygrep/releases/download/v0.7.0/ivygrep-v0.7.0-macos-x86_64.tar.gz"
      sha256 "0563528d418e71806c85ca11064f38d7c34c6d47eebe5eb8dd3c780dede8a16c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvolpato/ivygrep/releases/download/v0.7.0/ivygrep-v0.7.0-macos-aarch64.tar.gz"
      sha256 "92564ac8833110ff2e258f69cee70fdcbe78c5e1aa11abbc4ee107803df53a9a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bvolpato/ivygrep/releases/download/v0.7.0/ivygrep-v0.7.0-linux-x86_64-musl.tar.gz"
      sha256 "72825d59415449daa22c108011837a5f60763d0c0ab0a409f165fbdc7f5fa85f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvolpato/ivygrep/releases/download/v0.7.0/ivygrep-v0.7.0-linux-aarch64-musl.tar.gz"
      sha256 "a66512d4edb525097c950c1fe5501237a6b8302ff1bc552035e273e3aabf2141"
    end
  end

  def install
    bin.install "ig"
  end

  test do
    (testpath/"hello.rs").write('fn hello() -> &str { "world" }')
    system "#{bin}/ig", "--help"
  end
end
