# typed: false
# frozen_string_literal: true

# This file is auto-generated by the ivygrep release workflow. DO NOT EDIT.
class Ivygrep < Formula
  desc "Semantic grep for codebases — hybrid lexical + vector search, local-only"
  homepage "https://github.com/bvolpato/ivygrep"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bvolpato/ivygrep/releases/download/v1.1.1/ivygrep-v1.1.1-macos-x86_64.tar.gz"
      sha256 "02090e33bd62dca55abcb4dad35d6cf5597a80fa1c9fc574d916bd6317bf0fd1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvolpato/ivygrep/releases/download/v1.1.1/ivygrep-v1.1.1-macos-aarch64.tar.gz"
      sha256 "d7138368f14726d09cee313c135b82d8c883188f628f815b835f2a957bbc5b74"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/bvolpato/ivygrep/releases/download/v1.1.1/ivygrep-v1.1.1-linux-x86_64-musl.tar.gz"
      sha256 "b4db0838ea585ab308e49b09f2ba21e03cc7693f2b31dd3bea40b8ef140b98dd"
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvolpato/ivygrep/releases/download/v1.1.1/ivygrep-v1.1.1-linux-aarch64-musl.tar.gz"
      sha256 "927180a5f4f2cdff84d9708b95359534e72ad5e79524096fabfec840a71e0f01"
    end
  end

  def install
    bin.install "ig"
  end

  test do
    (testpath/"hello.rs").write('fn hello() -> &str { "world" }')
    system "#{bin}/ig", "--help"
  end
end
