# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmdg < Formula
  desc "Native Mermaid renderer in Go without browser/chromium"
  homepage "https://github.com/bvolpato/mermaid-go-renderer"
  version "0.10.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/bvolpato/mermaid-go-renderer/releases/download/v0.10.1/mermaid-go-renderer_0.10.1_darwin_amd64.tar.gz"
    sha256 "f2d58cfae3ad8b76ae692b73c2b59d39e881e0fc5dc784c66807daba2d9d6df1"

    define_method(:install) do
      bin.install "mmdg"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/bvolpato/mermaid-go-renderer/releases/download/v0.10.1/mermaid-go-renderer_0.10.1_darwin_arm64.tar.gz"
    sha256 "e9088eadb0e0c28898ad39ae45b15ddc1028ea2d419fa09419732fc98b50d531"

    define_method(:install) do
      bin.install "mmdg"
    end
  end

  test do
    (testpath/"diagram.mmd").write("flowchart LR\nA --> B\n")
    system "#{bin}/mmdg", "-i", testpath/"diagram.mmd", "-o", testpath/"out.svg", "-e", "svg"
    assert_predicate testpath/"out.svg", :exist?
  end
end
