# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmdg < Formula
  desc "Native Mermaid renderer in Go without browser/chromium"
  homepage "https://github.com/bvolpato/mermaid-go-renderer"
  version "0.3.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/bvolpato/mermaid-go-renderer/releases/download/v0.3.4/mermaid-go-renderer_0.3.4_darwin_amd64.tar.gz"
    sha256 "83be4dbefa780abcd9e1db4644d5b88f0d83fc28492412842a88b782dfeab85f"

    define_method(:install) do
      bin.install "mmdg"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/bvolpato/mermaid-go-renderer/releases/download/v0.3.4/mermaid-go-renderer_0.3.4_darwin_arm64.tar.gz"
    sha256 "7234dad23c247e8ba09e0779e4c5f8927a2ebf17d31d5ab805d515bfdba5c9c4"

    define_method(:install) do
      bin.install "mmdg"
    end
  end

  test do
    (testpath/"diagram.mmd").write("flowchart LR\nA --> B\n")
    system "#{bin}/mmdg", "-i", testpath/"diagram.mmd", "-o", testpath/"out.svg", "-e", "svg"
    assert_predicate testpath/"out.svg", :exist?
  end
end
