# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmdg < Formula
  desc "Native Mermaid renderer in Go without browser/chromium"
  homepage "https://github.com/bvolpato/mermaid-go-renderer"
  version "0.8.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/bvolpato/mermaid-go-renderer/releases/download/v0.8.0/mermaid-go-renderer_0.8.0_darwin_amd64.tar.gz"
    sha256 "b42e7439bfc1c659e701a2cfb90e935e5aae83de2590a63d79db7f88b0047fc3"

    define_method(:install) do
      bin.install "mmdg"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/bvolpato/mermaid-go-renderer/releases/download/v0.8.0/mermaid-go-renderer_0.8.0_darwin_arm64.tar.gz"
    sha256 "504a8989e3b71bf7c93002ffd7e45d06495edda1ae3dc9ca7915ab62c601ef9c"

    define_method(:install) do
      bin.install "mmdg"
    end
  end

  test do
    (testpath/"diagram.mmd").write("flowchart LR\nA --> B\n")
    system "#{bin}/mmdg", "-i", testpath/"diagram.mmd", "-o", testpath/"out.svg", "-e", "svg"
    assert_predicate testpath/"out.svg", :exist?
  end
end
